config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  get "home/about"
  get "home/search"

  # post "/home/search" => "home/search"
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-info alert-dismissible fade show" role="alert">
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			<%= content_tag(:div, msg) %>
	</div>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Crypto", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search", home_search_path, class: "nav-link" %>
        </li>

      <% if user_signed_in? %>

        <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit", edit_user_registration_path , class: "nav-link" %>
        </li>

      <% else %>

        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path , class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path , class: "nav-link" %>
        </li>

      <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
About Us Tings

<p>
	<%= @about_Rory %>
</p>

app/views/home/index.html.erb
<ul>


<% for x in @coins['data'] %>
	<% for coin in @my_coins %>
		<% if coin == x["symbol"] %>
			<p>
				<li>
					Rank: <%= x["name"] %> <br/>
					Name: <%= x["name"] %> <br/>
					Symbol: <%= x["symbol"] %> <br/>
					Price: $<%= x["quote"]['USD']['price'] %> <br/>
				</li>
			</p>
		<% end %>
	<% end %>
<% end %>



</ul>

app/views/home/search.html.erb
<div class="card">
  <div class="card-header">
    <h4>Search</h4>
  </div>
  <div class="card-body">
    <p class="card-text">Enter the Crypto symbol below</p>
  
	<%= form_with url: home_search_path, method: :get do |form| %>
		<div class = "mb-3">
		  <%= form.text_field :query, placeholder: "eg.) BTC, ETH", class: "form-control" %> <br />
		  <%= form.submit "Search", class: "btn btn-primary" %>
	  </div>
	<% end %>

<br />
 <%= @symbol%>

 <%= @coins %>


 <% for x in @search_coin['data'] %>
		<% if @symbol == x["symbol"] %>
			<p>
				<li>
					Rank: <%= x["name"] %> <br/>
					Name: <%= x["name"] %> <br/>
					Symbol: <%= x["symbol"] %> <br/>
					Price: $<%= x["quote"]['USD']['price'] %> <br/>
				</li>
			</p>
		<% end %>
<% end %>


</div>
</div>